### ISSUE TITLE
Work in different directories

### ISSUE THREAD

**Issue by dink10** [ldez/go-git-cmd-wrapper#3]
Hi. I want to use your library but I do 
`output, err := git.Clone(
		clone.Repository(repository),
		clone.Directory(directory),
		git.Debugger(true),
	)`
After that I pushed commit and do
`
output, err := git.Pull(
		pull.Repository(repository),
		git.Debugger(true),
	)
`
As the result - nothing happened

How I can work with the same git in different folders?

**Comment by dink10** [comment]
Can you reopen it and answer? Something went wrong :)

**Comment by ldez** [comment]
`clone.Repository` and `pull.Repository` are really git options:
- https://git-scm.com/docs/git-clone
- https://godoc.org/github.com/ldez/go-git-cmd-wrapper/clone#Directory
- https://git-scm.com/docs/git-pull
- https://godoc.org/github.com/ldez/go-git-cmd-wrapper/pull#Repository

Those options are not a way to do a `cd`.
To do a `cd` you have to use `os.Chdir` https://godoc.org/os#Chdir

A quick example:

```go
package git_test

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/ldez/go-git-cmd-wrapper/clone"
	"github.com/ldez/go-git-cmd-wrapper/git"
)

func TestName(t *testing.T) {
	rootDir := "/tmp/gitexample/"

	// cleans test directory
	err := os.RemoveAll(rootDir)
	if err != nil {
		panic(err)
	}

	pwd, _ := os.Getwd()
	fmt.Println("PWD: ", pwd)

	// creates test directory
	err = os.MkdirAll(rootDir, 0755)
	if err != nil {
		panic(err)
	}

	fmt.Println("cd /tmp/gitexample/")
	err = os.Chdir(rootDir)
	if err != nil {
		panic(err)
	}

	pwd, _ = os.Getwd()
	fmt.Println("PWD: ", pwd)

	// git clone git@github.com:ldez/go-git-cmd-wrapper.git
	// output, err := git.Clone(clone.Repository(repository), clone.Directory(directory), git.Debugger(true))
	output, err := git.Clone(clone.Repository("git@github.com:ldez/go-git-cmd-wrapper.git"), git.Debugger(true))
	if err != nil {
		fmt.Println(output)
		panic(err)
	}
	fmt.Println(output)

	fmt.Println("cd go-git-cmd-wrapper")
	err = os.Chdir(filepath.Join(rootDir, "go-git-cmd-wrapper"))
	if err != nil {
		panic(err)
	}

	pwd, _ = os.Getwd()
	fmt.Println("PWD: ", pwd)

	// git pull
	output, err = git.Pull(git.Debugger(true))
	if err != nil {
		fmt.Println(output)
		panic(err)
	}
	fmt.Println(output)
}
```

Output:
```console
PWD:  /home/ldez/sources/go/src/github.com/ldez/go-git-cmd-wrapper/git

cd /tmp/gitexample/

PWD:  /tmp/gitexample

git clone git@github.com:ldez/go-git-cmd-wrapper.git
Cloning into 'go-git-cmd-wrapper'...

cd go-git-cmd-wrapper

PWD:  /tmp/gitexample/go-git-cmd-wrapper

git pull
Successfully rebased and updated refs/heads/master.
```

**Comment by dink10** [comment]
What I found out
`output, err := git.Raw(
		"-C",
		clone.Directory(path.Join(directory)),
		pullOption,
		pull.Repository(repository),
		git.Debugger(true),
	)`
works fine

**Comment by ldez** [comment]
The wrapper is just a wrapper around git so you need to do the same thing as you did when you are using a terminal, so you have to use `cd`  (`os.Chdir`)

FYI:
- `path.Join` is made to join multiple path fragments.
- you don't need to pull after a clone.
- you don't need `"-C"` you just need to do a `cd ` (`os.Chdir`)

**Comment by gemscoder** [comment]
Hi,
os.Chdir() is fine but only in single threaded environment.  For multi-threaded case, the only options is git.Raw, right?

**Comment by gemscoder** [comment]
> ```go
> git.Raw(
> 		"-C",
> 		clone.Directory(path.Join(directory)),
> 		pullOption,
> 		pull.Repository(repository),
> 		git.Debugger(true),
> 	)
> ```

Hi, what do you pass as pullOptions? Is it just "pull"

**Comment by EWitting** [comment]
In case anyone is also dealing with this and doesn't want to use `os.Chdir`, did some digging in the source code and came up with this custom Executor workaround. (Note: this also trims trailing newlines, unlike the default executor.)
```golang
// custom option made for use with the go-git-cmd-wrapper library,
// enables execution in specific paths, without using os.Chdir, which possibly interferes with other operations
func runGitIn(path string) types.Option {
	return git.CmdExecutor(
		func(ctx context.Context, name string, debug bool, args ...string) (string, error) {

			// insert -C "path" before the other arguments
			args = append([]string{"-C", path}, args...)

			output, err := exec.Command(name, args...).CombinedOutput()
			return strings.TrimSuffix(string(output), "\n"), err
		},
	)
}
```
Usage:
```golang
commitHash, err := git.RevParse(revparse.Args(branch), runGitIn(path))
```

**Comment by ldez** [comment]
you can do that:

```go
func runGitIn(path string) types.Option {
	return git.CmdExecutor(
		func(ctx context.Context, name string, debug bool, args ...string) (string, error) {
			cmd := exec.CommandContext(ctx, name, args...)
			cmd.Dir = path

			output, err := cmd.CombinedOutput()
			return strings.TrimSuffix(string(output), "\n"), err
		},
	)
}
```
