### ISSUE TITLE
How to add new commands

### ISSUE THREAD

**Issue by nolith** [ldez/go-git-cmd-wrapper#9]
Hello, I was looking at the library, and I am curious about how someone should contribute a new command.

Do you manually generate the `internal/descriptions.json`?

How do you create the `new-command/doc.go`? Is it just a cut & paste of the git help for that command?

If you could write a quick guide to add new commands, it could be easier for contributors to add some missing commands.

Thank you

**Comment by ldez** [comment]
Hello,

1. You must create a directory with the name of the command.
2. Inside this directory, you must create a `doc.go` with a summary of the git command (based of the help of this command).
3. You must define all the options inside [descriptions.json](https://github.com/ldez/go-git-cmd-wrapper/blob/main/internal/descriptions.json).
4. Optionally, you could create a `<command>_custom.go` inside the command directory to add option(s) which cannot be generated.
5. You must run `make generate` to generate the `<command>_gen.go` related to the `descriptions.json`.
6. Inside the command directory, you must add test `<command>_test.go`.
7. You must add tests inside [example_test.go](https://github.com/ldez/go-git-cmd-wrapper/blob/main/git/example_test.go)

**Comment by ldez** [comment]
I added a contributing guide: https://github.com/ldez/go-git-cmd-wrapper/blob/main/CONTRIBUTING.md
